### ISSUE TITLE
Setting "-Dudger.autoupdate.time" in JAVA_OPTS  doesnt seem to trigger update at given time

### ISSUE THREAD

**Issue by ROLeLakas** [udger/udger-local-api#3]
## Setting "-Dudger.autoupdate.time=4:42" in JAVA_OPTS doesn't seem to be working.

"udger.autoupdate.time" variable seems to get set correctly when checked in the running container, but when the time comes, it doesn't execute the update.

From Dockerfile:
...
ENV JAVA_OPTS="-Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Dudger.db=/udgerdb/udger_test_v3.dat -Dudger.clientkey=%OUR_CLIENT_KEY% -Dudger.autoupdate.time=4:42"
...

However using REST API call "POST udger-local-api/set/autoupdate/?time=4:42" works just fine.

**Comment by skybber** [comment]
Thanks for report, it's fixed now, you should see scheduling message in log:

https://github.com/udger/udger-local-api/blob/master/src/main/java/org/udger/restapi/service/PoolManager.java#L124

I've upgraded project to meecrowave v1.2.10 as well.
